# Generated by Django 5.0.1 on 2025-11-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When job finished', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Optional job details'),
        ),
        migrations.AddField(
            model_name='job',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if job failed'),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.IntegerField(default=5, help_text='Job priority (1-10, higher is more important)'),
        ),
        migrations.AddField(
            model_name='job',
            name='resource_requirements',
            field=models.JSONField(blank=True, help_text='CPU/Memory requirements', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='result_data',
            field=models.JSONField(blank=True, help_text='Job output data', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to run the job', null=True),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='message',
            field=models.TextField(blank=True, help_text='Status details or notes'),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='progress',
            field=models.IntegerField(blank=True, help_text='Progress percentage (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='status_type',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority'], name='jobs_job_priorit_99845a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority', 'created_at'], name='jobs_job_priorit_6f43e4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatus',
            index=models.Index(fields=['job', 'timestamp'], name='jobs_jobsta_job_id_76d15c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatus',
            index=models.Index(fields=['status_type'], name='jobs_jobsta_status__2e0a07_idx'),
        ),
    ]
