# Generated by Django 5.0.1 on 2025-11-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_completed_at_job_description_job_error_message_and_more'),
        ('jobs', '0004_initial_data'),
    ]

    operations = [
    ]
